### ISSUE TITLE
Book appointment is not working

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#10]
Exception error is being thrown when I inserts data in form and click on submit button
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/d2a7f960-cc43-40a9-80e6-ad15cc392f71)

**Comment by Marc151104** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/145473896/e9a61040-8bef-49bb-846c-bb1b56febd2f)

**Comment by Japoivvb** [comment]
working as requested, great job
