### ISSUE TITLE
Contact us form is not working

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#11]
After insert data and click on "Send Message" an exception is thrown
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/34d99a84-8f77-49cd-b860-5a7d697bd6d1)

**Comment by Omirzar1337** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/65012775/eb6c0c48-cdfe-4c6c-9b52-99ad2ec5f32b)

![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/65012775/632180ec-1e1a-4062-a91b-d1b3cf5b6b93)

**Comment by Japoivvb** [comment]
confirmed, it is working.
