### ISSUE TITLE
Admin nurses does not work throwing an exception

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#12]
when I click on nurses in admin menu an error is shown like this

![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/bb3f54ea-756d-4ee2-92d1-060f1e9ebaf6)

**Comment by salimtamaichi** [comment]
![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/145464268/28732eb3-597d-44c7-bf74-470f1aefd0c4)

**Comment by Japoivvb** [comment]
please include new seeder inside call function of DatabaseSeeder in order to be called at the beginning of installation
https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/blob/main/database/seeders/DatabaseSeeder.php#L61
it should be tested launched 
php artisan migrate:fresh --seed

please include #numberIssue in the commit message to link both things

**Comment by salimtamaichi** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/145464268/57963500-7d56-456a-82e0-903d163f8942)
Implemented the seeder at DatabaseSeeder function

**Comment by Japoivvb** [comment]
sorry Salim but the implementation should be follow same pattern than doctors, it means table nurses only should have an employee_id to get rest data from employee data, you will have to undo changes and analyze how it is working doctors model/seeder ...

**Comment by salimtamaichi** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/145464268/dc99b7ff-8ab2-4300-a1b5-4174a23dd99d)
Updated Nurses model and View

**Comment by Japoivvb** [comment]
excelent rework job Salim, sometimes undoing is harder task than doing.
