### ISSUE TITLE
Change patients seeder from QueryBuilder to Eloquent using corresponding model

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#127]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/bbf40dd6-8404-49a2-a232-3770ade68079)

**Comment by Abmz99** [comment]
![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146850600/ec46b7a5-21c5-4826-ad08-d7fedacdfc01)



![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146850600/ab1bc8bb-f7f6-4a58-b04e-103f875f8c1c)

**Comment by Japoivvb** [comment]
coded without any support and just few lines about it, well done.
