### ISSUE TITLE
No initial appointments data when application is installed

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#128]
Create a appointmentSeeder to have dummy initial data and included in DatabaseSeeder to be executed with first seed database, they have to be proper/existent patient and doctor id and with closed list values for status field.

**Comment by ValeryxRC** [comment]
They create appointmentSeeder
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146208386/c9acafd2-1eed-4fb2-829f-6fb26eaeafad)

**Comment by Japoivvb** [comment]
fine seeder but incompleted solution, any seeder must be included in main seeder in order to be executed when `php artisan migrate:fresh --seed` is launched
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/fe5762c5-071c-4fac-a5f6-ce272a9f2c7c)

**Comment by ValeryxRC** [comment]
They seeder  included in main seeder
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146208386/52047104-f7f1-4fe3-88d7-34d75867d89a)

**Comment by Japoivvb** [comment]
good job, done as expected
