### ISSUE TITLE
Url included twice the admin word for HODs section

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#13]
Please leave only 1 admin in link

![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/9d56e1f5-8b97-4088-8b14-b7739e4f8f54)

**Comment by Japoivvb** [comment]
please add a screenshoy after change to verify it is still working the url after change the web.php, once uploaded I will verify to close the issue

**Comment by aherrert** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/77837668/77073cc4-2b5b-4f97-a5ac-6e9a9b9b1847)

**Comment by Japoivvb** [comment]
it is not working, it seems your change has been missed in main master
https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/blob/88430fed1821e44668e438188d13ff3f922c810c/routes/web.php#L62
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/aad704d1-b07e-43f5-b0d4-4332e13c9c31)

**Comment by aherrert** [comment]
If I have seen it now, it was with arnau when I changed the file and copied
it from xavi's file, I think that is where that problem comes from

**Comment by Japoivvb** [comment]
you are absolutely right, good analysis, you will have to edit again web.php to have a new version with all changes integrated (docter, suscribers and your own change about hod)

**Comment by Japoivvb** [comment]
working, do not forget next time to attach evidence it is tested by you
