### ISSUE TITLE
Patients form is not updating gender

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#131]
although a message is showed as 
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/f40a1b0c-ebea-4083-b5e5-9d68b3b8478d)

the change is not done in database
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/0d48bb1e-4ea0-4f5a-a220-83ef1ffca857)

listed in admin site
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/dfe5ccb2-5811-47cd-96ba-dc15405b8c35)

in database, still male
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/21e785cb-17be-4257-bbae-f8c5f2ec9736)

**Comment by Dzn12** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146850908/3291b49f-279b-4589-93e9-0ebbd1e3cd76)

**Comment by Japoivvb** [comment]
great, confirmed it is working fine
