### ISSUE TITLE
No initial patients data when application is installed

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#14]
Create a patientSeeder to have dummy initial data and included in DatabaseSeeder to be executed with first seed database

**Comment by Japoivvb** [comment]
excellent and fast job but although I verified it is working in my machine you need to attach evidence is working in the issue
e.g. screenshot from admin/patients and data rows from table

**Comment by aherrert** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/77837668/cf4d72cf-59d2-4307-93fb-0cd2c41c29dc)

**Comment by Japoivvb** [comment]
confirmed, it is working, well done
