### ISSUE TITLE
Alter order softDeletes field in nurses to have same as other tables

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#144]
modify migration file to create table nurses with proper order, as doctor for example
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/2c93f62f-cbf4-4721-acd9-39a84a96a81b)

to be
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/0b699208-63e5-4954-a8f5-5f2db929809f)

**Comment by IsabelArellano** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/115017603/349ef183-54f5-4b02-9daf-048760b540b0)

**Comment by Japoivvb** [comment]
migration file works fine, closed
