### ISSUE TITLE
stays amount fields should be decimal but varchar

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#145]
fields in scope change
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/3c06761e-f76a-4e9a-b9fe-a69d72dbf046)
adapt any component impacted also, it means seeder, migration ...

**Comment by Omirzar1337** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/65012775/c894ff00-c606-497a-b8ae-420fcd15e313)
