### ISSUE TITLE
create API to list all medicines

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#16]
define a new api route with name medicines to list all medicines stored

**Route**
- name: medicines
- method: get

**Controller**
- name: MedicinesController
- function: getAllMedicines

**Comment by Kevin9SA** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/135112054/16886519-6b48-4c98-a178-a5849aa75a40)

**Comment by Japoivvb** [comment]
it works but a little change must be done before close it
"any controller should extends from Controller class" next time create it using artisan make controller command

**Comment by Japoivvb** [comment]
fine, now every component is right, good job
