### ISSUE TITLE
Symptom check using external API

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#163]
investigate how to call and required components to integrate the api
https://endlessmedical.com/about-endlessmedical-api/

**Comment by NabilHG** [comment]
Here you have the url to analyze, the array you have to send and a sample of the request:
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/125380442/1f9e7903-f639-405b-8bf7-62b3b83371c0)
