### ISSUE TITLE
Error editing a medicines on click edit icon

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#17]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/eea62aad-e070-47cf-9cd1-aa309dd7bf0a)

![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/9f3eb820-33c1-4136-ae91-835c84f70fc6)

**Comment by salimtamaichi** [comment]
![Captura](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/145464268/2aa2d9f8-50ab-4955-93a2-9fd34ef64dfb)

**Comment by Japoivvb** [comment]
let's talk about the final fix today, once you must attach again the evidence if it is working.

**Comment by Japoivvb** [comment]
fixed after apply update livewire command, remember upload the evidence once it is working
e.g.
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/965d6885-f8ed-41cc-baff-9f8146c0fd43)
