### ISSUE TITLE
Error adding a new block

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#18]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/17e2d49e-6395-444c-9764-089bbd85051a)

![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/a9b20b8d-a8fe-492b-9490-e91a379ebd24)

**Comment by NabilHG** [comment]
Solution:
![Captura de pantalla_2024-03-05_19-08-08](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/125380442/891b8ebd-7847-4c1c-bfc3-a572549c5d80)

**Comment by Japoivvb** [comment]
well done, next similar issue let's try to use an alert in application, some people did not read the discussion email.

And please better evidence if you attach screens from application of involved use case, in this case how to add a block
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/743139ec-8d36-42cd-83d5-20553bcfed14)
