### ISSUE TITLE
Tensorflow integration for Laravel

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#183]
train a model with images e.g. diseases 
https://teachablemachine.withgoogle.com/

use in laravel
https://cubettech.com/resources/blog/building-ai-powered-web-applications-with-laravel/

**Comment by NabilHG** [comment]
[project.zip](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/files/15325118/project.zip)
