### ISSUE TITLE
Modify view to avoid error in admin/beds without null patients

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#196]
in case a bed does not have patient an error is thrown from admin/beds
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/4c09d9ea-ab07-4760-9d85-0fb3c2978a68)

taking advantage to modify corresponding seeder to link some beds with some patients by id also

**Comment by TrueTechV0** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/147527611/914ed2f9-3536-4d86-b632-08d42a5466f2)
