### ISSUE TITLE
Main logo in div home is missed

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#2]
Add a proper icon related with information showed in this section
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/a3bb9f6f-192e-4f82-87a6-2af4d91514cf)

**Comment by iLevyyy** [comment]
![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/89799212/9c016d83-2963-4505-a7e5-e7d17b89f56e)

**Comment by Japoivvb** [comment]
verified
