### ISSUE TITLE
Build livewire Patients component for "Symptom Check"

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#200]
.app\Http\Livewire\Patients\SymptomCheck.php (add, delete, analyze(call API medicall and show results),render)
-> return view('livewire.patients.symptomcheck')->layout('patients.layouts.app');
setRequest
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/c6af39d0-2f66-4201-951f-44694f3ac1f3)
getResponse
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/99e58c46-1a6b-4e60-b825-9e66bb7ab5cb)

**Comment by IsabelArellano** [comment]
![Form](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/115017603/0bf5ae1c-950e-43d5-bc6b-9387f508dc07)
![Result](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/115017603/460f50a3-f831-49c6-ae1a-4b0a372765d7)

**Comment by Japoivvb** [comment]
good job, mark will be updated, keep on mind next commit must have reference issue with # character, I added by comment
