### ISSUE TITLE
Fix mistypo docter in all references of application

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#21]
please change value to doctor

![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/a4c39702-9df6-4286-92ef-cbd347bec94b)

**Comment by x4v1k** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146961654/9f8a53d8-8012-4b91-9222-4e98b8a6b1af)
