### ISSUE TITLE
Fix source error in Bills component

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#27]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/bb2b1e07-c4b0-455c-a9ad-f94a3becb40e)

**Comment by Aakriti313** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/135099626/604427d3-6193-49b6-95bc-b88a2c68a9dd)


<img width="545" alt="bills" src="https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/135099626/9f63df3f-a69f-40fd-8d22-b94a6946f91f">

**Comment by Japoivvb** [comment]
well done, good idea to take another similar issue in same functionality to have more context in order to take decissions.
