### ISSUE TITLE
Fix undefined error in all render() function of Livewire components

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#28]
Although it seems it is working, to avoid errors in promotion code, please adapt all render functions, keep on mind there are about 20 files impacted for this change.

![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/778107df-68d1-49d6-b502-36a2deea09b4)

**Comment by iLevyyy** [comment]
![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/89799212/14710922-c679-4d2f-8ed4-ee2fb5121e86)



![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/89799212/2d051257-accf-4f8f-828e-da5419335bad)

**Comment by Japoivvb** [comment]
working, good job, please keep on mind next commit should have the message with #number to track it with the corresponding issue
