### ISSUE TITLE
Logo in div about is missed

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#3]
Add a proper icon related with information showed in this section
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/3876e468-9074-4950-8401-e33af0c8bac8)

**Comment by AlexViza** [comment]
![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146524960/017846bc-3fe8-4a64-a031-b68304284ada)
