### ISSUE TITLE
Fix source password property in Patients component

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#30]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/4eeeccda-22c7-45be-9b6a-dc315b2e54e1)

**Comment by Marc151104** [comment]
![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/145473896/2a9deb57-a986-4d90-8ccd-d28d827ee217)

**Comment by Japoivvb** [comment]
good job, next time upload a screenshot of application also to verify the functionality is working fine e.g.
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/a5b77c7b-049d-4907-afb4-bb4f43165cb5)
