### ISSUE TITLE
Fix source errors in Settings component

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#31]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/fa59d0d4-9454-42d7-b510-0bd9091d6205)

![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/08d94d5f-081e-4fc1-a6c3-cc006167e963)

**Comment by cesarorrr** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/145366857/88e89709-0a98-4f9a-8b1e-8e65ca91746d)
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/145366857/71566db1-d399-472f-8330-22eb85d2465a)
