### ISSUE TITLE
create API to list all doctors

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#33]
define a new api route with name doctors to list all doctors stored showing data employee for each one

**Route**
- name: doctors
- method: get

**Controller**
- name: DoctorsController
- function: getAllDoctors

**Comment by AlexViza** [comment]
![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146524960/b3f53521-d10c-4450-a072-a363be9167f1)

**Comment by Japoivvb** [comment]
fine but incompleted, it was requested "doctors stored showing data employee for each one" you must join doctors table plus employee to get it.

**Comment by AlexViza** [comment]
![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146524960/dbf1f321-f4d2-422a-a52d-f14e0abcf627)
