### ISSUE TITLE
create API to list all patients

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#34]
define a new api route with name patients, not including doctor data

**Route**
- name: patients
- method: get

**Controller**
- name: PatientsController
- function: getAllPatients

**Comment by Japoivvb** [comment]
1. any controller should extends from Controller class
2. commit message should have #numberissue to be tracked easier from here
3. in order to close, an evidence should attach in issue of functionality working, this case sample req/response from Postdata app

**Comment by Tomvsa** [comment]
![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/110344395/d904538b-aa8e-4a92-84a1-d032e9db9797)

**Comment by Japoivvb** [comment]
fine but a little bit different than requested, please check the initial requirement "not including doctor data"

**Comment by Tomvsa** [comment]
![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/110344395/80d7856a-1058-4908-bb7d-a7ea2ceba11f)

**Comment by Japoivvb** [comment]
everything is fine now, closing
