### ISSUE TITLE
create API to get stadistics of birth reports

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#37]
define a new api route to know:

- count birth reports total
- number by gender
- average by month

**Route**
- name: birth-reports/stats
- method: get

**Controller**
- name: BirthReportsController
- function: getBirthStats

**Comment by Japoivvb** [comment]
1. any controller should extend from Controller class
2. in order to close, an evidence should attach in issue of functionality working, this case sample req/response from Postdata app

**Comment by NabilHG** [comment]
Good morning, Jose.

Sorry, I put the evidence in the conversation at the merge request. I get
done the first point ad put the evidence in the correct place in a moment.

**Comment by NabilHG** [comment]
I think is already done, the commit name is «fixed silly mistake, now BirthController extends from Contrller »

**Comment by Japoivvb** [comment]
verified, nothing is pending to do.
