### ISSUE TITLE
Change header duplicated Specialist Clinic by Our Team and with its own icon

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#4]
Div doctors has same header than previous one, change to Our Team and add icon related with it
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/7ff10f50-5f2d-4066-9968-cae3998d5c33)

**Comment by AlexViza** [comment]
![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146524960/052faabd-4941-4ff1-8f41-0114dbac73d0)

**Comment by Japoivvb** [comment]
good job, be careful in commit message to have #numberIssue proper written to link with issue. I mean issue#4 with one space before #.
