### ISSUE TITLE
No initial stays data when application is installed

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#41]
Create a staysSeeder to have dummy initial data and included in DatabaseSeeder to be executed with first seed database, they have to be proper/existent patient id also

**Comment by Omirzar1337** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/65012775/11417110-5e65-409e-9386-eab93707f2f5)
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/65012775/bbdfd9ce-d009-40d1-97a1-788b951937d3)

**Comment by Japoivvb** [comment]
well done, I will open other issue to change those economic fields from varchar to decimal to be more accurate in which data is stored inside them.
