### ISSUE TITLE
Patient form in admin/patients page is not working after click on "Add New Patient" button

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#43]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/205afc86-2c4c-4849-ad31-838325b5a667)

**Comment by ValeryxRC** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146208386/120e1fbf-c6c4-4527-b64d-9b86c3f930ba)
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146208386/4c84ab3d-f0c4-492f-9a69-bcac589495da)
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146208386/69a6b36b-887d-4414-ad3d-3f67dd7c185e)

**Comment by Japoivvb** [comment]
great, let's see if people read and do it or just click "Accept" directly :) next alert include a hyperlink to readme file
