### ISSUE TITLE
Medicine form in admin/medicinesStore allow duplicate code in database

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#47]
change primary key to include code as unique value

![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/c7bd045d-b0bc-4a37-a4bb-abc9ce2bdf3d)

**Comment by Kevin9SA** [comment]
The first pictures is the old one: 

![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/135112054/7e3034de-9f2a-443a-9f63-03eeb5dca90e)

This is when you ejaculate de migration with the alter-table  medicines:
Now the code is a UNIQUE value: you need to do this command: php artisan migrate  

![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/135112054/b48865cb-d14f-43f8-a1f6-324b1a0d05c4)

**Comment by Japoivvb** [comment]
working but a user friendly error should be showed instead QueryException
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/9e9e7a63-d787-4836-83ca-c90884df1c0b)
check some solution to apply in validate() for add_medicine function from resources\lang\en\validation.php

**Comment by Kevin9SA** [comment]
![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/135112054/33ac4417-1a5d-495b-84bc-9fbceef18b75)



![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/135112054/6c321281-f417-4489-ad52-c2730edbb5bf)

**Comment by Japoivvb** [comment]
much better for the user, closed after verification
