### ISSUE TITLE
Fix mistypo room status in All rooms list of admin/rooms

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#48]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/06c5e4fb-cf2b-4047-aafc-a70c840fc847)

**Comment by Omirzar1337** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/65012775/ab2aea03-abe1-4809-b00f-db057e148129)

**Comment by Japoivvb** [comment]
Sorry, it was a functional gap, if the values to show are available, occupied, maintenance the proper value for this column should be as database, so please change it again with value "Status"

**Comment by Omirzar1337** [comment]
I don't think I understand what you mean. We discuss it later

**Comment by Omirzar1337** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/65012775/897a616c-148b-4a54-b4e0-98fa8daa7e2a)

**Comment by Japoivvb** [comment]
now it is aligned column view, table and content data, thanks
