### ISSUE TITLE
create API to update payed field to paid by patient id

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#49]
define a new api route to update the bill to true for given patient Id, this api will be consumed for a third party finance system

**Route**
- name: bills/{patient_id}/status
- method: put

**Controller**
- name: BillsController
- function: payBill
- update bills.status to value "paid"

**Comment by Japoivvb** [comment]
although I saw it is working in your local machine, I would need an evidence here in the issue to verify it is working and document how to execute the api.
please attach a screenshot from postman showing req and response.

**Comment by Abmz99** [comment]
![bills](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146850600/06526150-b5d4-4204-9489-fc665c1ca43c)
![postmanbills](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146850600/ec8762ba-9fa6-447b-9048-045f153957e5)

**Comment by Japoivvb** [comment]
thanks for the evidence, closed
