### ISSUE TITLE
Logo in section testimonials is missed

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#5]
Add a proper icon related with information showed in this section
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/a91b91ed-49cb-4474-94f1-cca2e3237fbf)

**Comment by IvanSanz86** [comment]
![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146849161/ed6a3260-5873-465d-a2ff-e210082dcfc2)

**Comment by Japoivvb** [comment]
closed, all instructions about commit message, attach evidence, move to QA ... were done, well done.
