### ISSUE TITLE
Get in touch section is showed duplicated

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#6]
This section should appear only once with its corresponding icon

![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/d0793b72-7424-4984-a058-46e861c771ac)

**Comment by ValeryxRC** [comment]
#6 Fixed Issue 
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146208386/3d2fd45e-d207-417c-bbc2-35df073039aa)

**Comment by Japoivvb** [comment]
perfect Valery, everything as was requested
