### ISSUE TITLE
Modify README to include a step configuration to create schema/database hms

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#67]
in order to have a smooth installation of project in local please add a step to create database hms before execute seed db, if it is possible by command php artisan instead to do in SQL side using an external editor

![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/dfdc2e88-c6c2-4731-b558-d0c83ff8f25d)

**Comment by Omirzar1337** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/65012775/ab17f212-a6f0-4b68-97fd-aec7c01ef4cb)

**Comment by Japoivvb** [comment]
it is working perfect, I love the idea, I am sure this will help to set up easier the environment
