### ISSUE TITLE
Change main contact number in home page

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#7]
Finally we have the phone to be used, please update wrong phone number to +93 12 34 56
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/09e47b1a-5064-4f0b-9faa-9572dd72940b)

**Comment by Alvaro-IGJU** [comment]
![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/127084235/75eac214-fefe-49cd-8f27-ba60bc5f6fc3)

**Comment by Japoivvb** [comment]
working, although it will be interesting remove these hard codes from blade view and take it from hms.settings table, it will be open as enhancement
