### ISSUE TITLE
Room available form is a boolean value, but close list values

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#70]
we have different values to save in available field as
"available, occupied, maintenance"
but form is only a check, please adapt form in admin/rooms to add new room with possible values
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/4c1646a5-7b1e-42b4-9de1-75fa31c98a11)

**Comment by iLevyyy** [comment]
![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/89799212/9d217ac9-a3ce-479e-9648-ecd3bb02d0bb)





![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/89799212/768e5e03-1aa9-49d4-8881-5fade99cf8e2)



![Image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/89799212/e38430f6-3235-403e-9920-9a1e3ff9055c)

**Comment by Japoivvb** [comment]
working, better design to choose the possible value
