### ISSUE TITLE
Fix security issue about dependencies version of follow-redirects

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#78]
https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/security/dependabot/1

**Comment by x4v1k** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/146961654/c4915d02-8098-419a-a53d-e916ad8d2789)

**Comment by Japoivvb** [comment]
excellent, the bot closed the issue also when it saw your change
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/371c054d-4f83-42ee-aaa0-016c2188e4bd)
