### ISSUE TITLE
Doctor seeder is inserting only 2 doctor with same employee id

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#93]
Please fix corresponding seeder to add at least 5 doctors with different employee id

![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/bb7211a3-2ef9-42aa-aa9d-0c4a6759814c)

**Comment by Omirzar1337** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/65012775/a75eae94-e779-4ddc-a354-4f5bc0052f5f)

**Comment by Omirzar1337** [comment]
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/65012775/392f953a-2e30-4a49-845e-c3a1cf866638)

**Comment by Japoivvb** [comment]
working
